/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/components/movies/MovieHorizontal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/save` | `/save`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/actions/app-api`; params?: Router.UnknownInputParams; } | { pathname: `/components/MovieCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/TrandingCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/movies/MainSlides`; params?: Router.UnknownInputParams; } | { pathname: `/components/movies/MoviePoster`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useMovie`; params?: Router.UnknownInputParams; } | { pathname: `/infraestructure/mappers/movie.mapper`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/services/appwrite`; params?: Router.UnknownInputParams; } | { pathname: `/services/useFetch`; params?: Router.UnknownInputParams; } | { pathname: `/movies/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/components/movies/MovieHorizontal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/save` | `/save`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/actions/app-api`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MovieCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/TrandingCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/movies/MainSlides`; params?: Router.UnknownOutputParams; } | { pathname: `/components/movies/MoviePoster`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useMovie`; params?: Router.UnknownOutputParams; } | { pathname: `/infraestructure/mappers/movie.mapper`; params?: Router.UnknownOutputParams; } | { pathname: `/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/services/appwrite`; params?: Router.UnknownOutputParams; } | { pathname: `/services/useFetch`; params?: Router.UnknownOutputParams; } | { pathname: `/movies/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/components/movies/MovieHorizontal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/save${`?${string}` | `#${string}` | ''}` | `/save${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/actions/app-api${`?${string}` | `#${string}` | ''}` | `/components/MovieCard${`?${string}` | `#${string}` | ''}` | `/components/SearchBar${`?${string}` | `#${string}` | ''}` | `/components/TrandingCard${`?${string}` | `#${string}` | ''}` | `/components/movies/MainSlides${`?${string}` | `#${string}` | ''}` | `/components/movies/MoviePoster${`?${string}` | `#${string}` | ''}` | `/hooks/useMovie${`?${string}` | `#${string}` | ''}` | `/infraestructure/mappers/movie.mapper${`?${string}` | `#${string}` | ''}` | `/services/api${`?${string}` | `#${string}` | ''}` | `/services/appwrite${`?${string}` | `#${string}` | ''}` | `/services/useFetch${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/components/movies/MovieHorizontal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/save` | `/save`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/actions/app-api`; params?: Router.UnknownInputParams; } | { pathname: `/components/MovieCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/TrandingCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/movies/MainSlides`; params?: Router.UnknownInputParams; } | { pathname: `/components/movies/MoviePoster`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useMovie`; params?: Router.UnknownInputParams; } | { pathname: `/infraestructure/mappers/movie.mapper`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/services/appwrite`; params?: Router.UnknownInputParams; } | { pathname: `/services/useFetch`; params?: Router.UnknownInputParams; } | `/movies/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/movies/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
